apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kafka
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kafka-exporter'
        static_configs:
          - targets: ['kafka-exporter.kafka.svc.cluster.local:9308']
